#! /usr/bin/env sh


cd ~
# mkdir repos

REPO_URL=https://github.com/nielsberglund/dotfiles.git
REPO_PATH="$HOME/repos/dotfiles"

reset_color=$(tput sgr 0)

info() {
  printf "%s[*] %s%s\n" "$(tput setaf 4)" "$1" "$reset_color"
}

success() {
  printf "%s[*] %s%s\n" "$(tput setaf 2)" "$1" "$reset_color"
}

err() {
  printf "%s[*] %s%s\n" "$(tput setaf 1)" "$1" "$reset_color"
}

warn() {
  printf "%s[*] %s%s\n" "$(tput setaf 3)" "$1" "$reset_color"
}

install_homebrew() {
  export HOMEBREW_CASK_OPTS="--appdir=/Applications"
  if hash brew &>/dev/null; then
    warn "Homebrew already installed"
  else
    info "Installing homebrew..."
    sudo --validate  # reset `sudo` timeout to use Homebrew install in noninteractive mode
    CI=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi
}

info "Prompting for sudo password..."
if sudo -v; then
    # Keep-alive: update existing `sudo` time stamp until `setup.sh` has finished
    while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
    success "Sudo credentials updated."
else
    error "Failed to obtain sudo credentials."
fi

info "####### dotfiles #######"
read -p "Press enter to start:"
info "Bootstrapping..."

install_homebrew

# write to .zprofile
echo PATH=/opt/homebrew/bin:$PATH >> ~/.zprofile
source ~/.zprofile
export PATH=/opt/homebrew/bin:$PATH


info "Installing Git"
brew install git

# install the git credential manager
info "Installing Git Credential Manager"
brew install --cask git-credential-manager

info "Cloning .dotfiles repo from $REPO_URL into $REPO_PATH"
git clone "$REPO_URL" "$REPO_PATH"

info "Change path to $REPO_PATH"
cd "$REPO_PATH" >/dev/null

# ./setup.sh


