# tap "azure/functions"
# tap "homebrew/bundle"
# tap "homebrew/cask-versions"
# tap "homebrew/services"
tap "isen-ng/dotnet-sdk-versions"
tap "microsoft/git"
tap "romkatv/powerlevel10k"
brew "azure-cli"
brew "git"
brew "hugo"
brew "mas"
# brew "openjdk"
# brew "maven"
brew "pandoc"
brew "powerlevel10k"
# brew "azure/functions/azure-functions-core-tools@4"
cask "alt-tab"
# cask "azure-data-studio"
cask "citrix-workspace"
cask "cleanmymac"
cask "docker"
cask "dotnet-sdk"
cask "easyfind"
cask "firefox"
cask "gimp"
cask "git-credential-manager"
cask "google-chrome"
cask "grammarly-desktop"
cask "iterm2"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "microsoft-excel"
cask "microsoft-powerpoint"
cask "microsoft-word"
cask "miniforge"
cask "postman"
cask "snagit"
cask "sublime-text"
# cask "visual-studio-code"
cask "visual-studio-code@insiders"
cask "cursor"
cask "vlc"
mas "OneDrive", id: 823766827
